# For more info on HTTP files go to https://aka.ms/vs/httpfile

@baseUrl = http://localhost:5017

### Login Admin 200
POST {{baseUrl}}/login
Content-Type: application/json
{"usuario": "admin", "senha": "@admin12345"}

### Login Admin 401
POST {{baseUrl}}/login
Content-Type: application/json
{"usuario": "admin", "senha": "#admin12345"}


### Login User 200
POST {{baseUrl}}/login
Content-Type: application/json
{"usuario": "usuario01", "senha": "#Usuario01"}

### Login User 200
POST {{baseUrl}}/login
Content-Type: application/json
{"usuario": "usuario01", "senha": "@Usuario01"}


### Biblioteca User 200
GET {{baseUrl}}/biblioteca-jogos?codigo_usuario=ok
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c3VhcmlvMDEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwianRpIjoiZWYwYjE0N2EtODgzZC00ZTI5LWJjMmEtNDlhMTFkNTQ4NGQ1IiwiZXhwIjoxNzc3MzQwNjU0LCJpc3MiOiJBcHBGaWFwRmNHYW1lcyJ9.5Nr5Q-u-YhvxV0w3ln50P66vuqnqcRePFBfJsqX1ef8

### Biblioteca User 204
GET {{baseUrl}}/biblioteca-jogos?codigo_usuario=204
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c3VhcmlvMDEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwianRpIjoiZWYwYjE0N2EtODgzZC00ZTI5LWJjMmEtNDlhMTFkNTQ4NGQ1IiwiZXhwIjoxNzc3MzQwNjU0LCJpc3MiOiJBcHBGaWFwRmNHYW1lcyJ9.5Nr5Q-u-YhvxV0w3ln50P66vuqnqcRePFBfJsqX1ef8

### Biblioteca Admin 401
GET {{baseUrl}}/biblioteca-jogos?codigo_usuario=ok
Authorization: Bearer token
